version: '3.9'

services:
  mysql:
    container_name: db_base_mysql
    image: mysql:5.7
    restart: always
    # env_file: ./.env
    ports:
      - 3306:3306
    volumes:
      - ./base_db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=base_db
      - MYSQL_DATABASE=base_db